name = "MonteCarloMeasurements"
uuid = "0a594e34-94bc-4f62-947f-4b31ef19552b"
authors = ["W. Joe Meese <meese022@umn.edu> and contributors"]
version = "0.1.0"

[deps]
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
OnlineLogBinning = "6694b27a-7f2b-41da-9dea-d3f4793b6534"
TelegraphNoise = "843dd301-5ab4-451e-a248-fc72ff48def4"

[compat]
OnlineLogBinning = "0.2.2"
Measurements = "2"
TelegraphNoise = "0.1"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
